// <auto-generated />
namespace EmployeeCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_subscription_date_payment_form : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_subscription_date_payment_form));
        
        string IMigrationMetadata.Id
        {
            get { return "202112262012378_add_subscription_date_payment_form"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
