// <auto-generated />
namespace EmployeeCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatePaymentForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatePaymentForm));
        
        string IMigrationMetadata.Id
        {
            get { return "202201250814447_updatePaymentForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
