//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCare.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeCare.Resources.ar", typeof(ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسب.
        /// </summary>
        public static string accountant {
            get {
                return ResourceManager.GetString("accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفُعل.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جهة.
        /// </summary>
        public static string add_destination {
            get {
                return ResourceManager.GetString("add_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة وثيقه.
        /// </summary>
        public static string add_document {
            get {
                return ResourceManager.GetString("add_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه درجة وظيفية.
        /// </summary>
        public static string add_grade {
            get {
                return ResourceManager.GetString("add_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه نوع سداد.
        /// </summary>
        public static string add_payment_type {
            get {
                return ResourceManager.GetString("add_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم.
        /// </summary>
        public static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعية رعاية العاملين بقطاع التعمير و الأجهزة التابعة.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string birth_date {
            get {
                return ResourceManager.GetString("birth_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر ملف.
        /// </summary>
        public static string choose_file {
            get {
                return ResourceManager.GetString("choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات التواصل.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظه.
        /// </summary>
        public static string copy_rights {
            get {
                return ResourceManager.GetString("copy_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف.
        /// </summary>
        public static string delete_confirmation {
            get {
                return ResourceManager.GetString("delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string destination_name {
            get {
                return ResourceManager.GetString("destination_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهات.
        /// </summary>
        public static string destinations {
            get {
                return ResourceManager.GetString("destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئول استمارات.
        /// </summary>
        public static string docments_user {
            get {
                return ResourceManager.GetString("docments_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الوثائق.
        /// </summary>
        public static string document_types {
            get {
                return ResourceManager.GetString("document_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الجهة.
        /// </summary>
        public static string edit_destination {
            get {
                return ResourceManager.GetString("edit_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل وثيقة.
        /// </summary>
        public static string edit_document {
            get {
                return ResourceManager.GetString("edit_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الدرجة الوظيفية.
        /// </summary>
        public static string edit_grade {
            get {
                return ResourceManager.GetString("edit_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع سداد.
        /// </summary>
        public static string edit_payment_type {
            get {
                return ResourceManager.GetString("edit_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string edit_user {
            get {
                return ResourceManager.GetString("edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الألكتروني.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الموظفين.
        /// </summary>
        public static string employee_data {
            get {
                return ResourceManager.GetString("employee_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثي.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم بالكامل.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجات الوظيفية.
        /// </summary>
        public static string grades {
            get {
                return ResourceManager.GetString("grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفُعل.
        /// </summary>
        public static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة المرور غير صحيحة.
        /// </summary>
        public static string invalid_username_password {
            get {
                return ResourceManager.GetString("invalid_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول لنظام جمعية رعاية العاملين.
        /// </summary>
        public static string login_page_title {
            get {
                return ResourceManager.GetString("login_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string main_page {
            get {
                return ResourceManager.GetString("main_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عنوان.
        /// </summary>
        public static string no_address {
            get {
                return ResourceManager.GetString("no_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بريد الكتروني.
        /// </summary>
        public static string no_email {
            get {
                return ResourceManager.GetString("no_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد رقم هاتف.
        /// </summary>
        public static string no_phone {
            get {
                return ResourceManager.GetString("no_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اختيار نوع.
        /// </summary>
        public static string no_selected_gender {
            get {
                return ResourceManager.GetString("no_selected_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع السداد.
        /// </summary>
        public static string payment_types {
            get {
                return ResourceManager.GetString("payment_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        public static string primary_data {
            get {
                return ResourceManager.GetString("primary_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعاده تعيين.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر الجهة.
        /// </summary>
        public static string select_destination {
            get {
                return ResourceManager.GetString("select_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الصلاحية.
        /// </summary>
        public static string select_role {
            get {
                return ResourceManager.GetString("select_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار كلمة المرور.
        /// </summary>
        public static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الي.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم غير مفُعل.
        /// </summary>
        public static string user_not_actived {
            get {
                return ResourceManager.GetString("user_not_actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
