//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCare.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeCare.Resources.ar", typeof(ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسب.
        /// </summary>
        public static string accountant {
            get {
                return ResourceManager.GetString("accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات.
        /// </summary>
        public static string accountants {
            get {
                return ResourceManager.GetString("accountants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفُعل.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة بنك.
        /// </summary>
        public static string add_bank {
            get {
                return ResourceManager.GetString("add_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة قرار.
        /// </summary>
        public static string add_decision {
            get {
                return ResourceManager.GetString("add_decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جهة.
        /// </summary>
        public static string add_destination {
            get {
                return ResourceManager.GetString("add_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة وثيقه.
        /// </summary>
        public static string add_document {
            get {
                return ResourceManager.GetString("add_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة موظف.
        /// </summary>
        public static string add_employee {
            get {
                return ResourceManager.GetString("add_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة مستندات.
        /// </summary>
        public static string add_files {
            get {
                return ResourceManager.GetString("add_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه درجة وظيفية.
        /// </summary>
        public static string add_grade {
            get {
                return ResourceManager.GetString("add_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايصاد جديد.
        /// </summary>
        public static string add_invoice {
            get {
                return ResourceManager.GetString("add_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة استمارة.
        /// </summary>
        public static string add_payment_form {
            get {
                return ResourceManager.GetString("add_payment_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه نوع سداد.
        /// </summary>
        public static string add_payment_type {
            get {
                return ResourceManager.GetString("add_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة الي الارشيف.
        /// </summary>
        public static string add_to_archive {
            get {
                return ResourceManager.GetString("add_to_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم.
        /// </summary>
        public static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملبغ.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعية رعاية العاملين بقطاع التعمير و الأجهزة التابعة.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد.
        /// </summary>
        public static string approval_status {
            get {
                return ResourceManager.GetString("approval_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفات الارشيف.
        /// </summary>
        public static string archive_documens {
            get {
                return ResourceManager.GetString("archive_documens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم حساب البنك.
        /// </summary>
        public static string bank_account_number {
            get {
                return ResourceManager.GetString("bank_account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنوك.
        /// </summary>
        public static string banks {
            get {
                return ResourceManager.GetString("banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string birth_date {
            get {
                return ResourceManager.GetString("birth_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثمن الشيك.
        /// </summary>
        public static string cheque_cost {
            get {
                return ResourceManager.GetString("cheque_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشيك.
        /// </summary>
        public static string cheque_number {
            get {
                return ResourceManager.GetString("cheque_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر ملف.
        /// </summary>
        public static string choose_file {
            get {
                return ResourceManager.GetString("choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات التواصل.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظه.
        /// </summary>
        public static string copy_rights {
            get {
                return ResourceManager.GetString("copy_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وفاه.
        /// </summary>
        public static string dead {
            get {
                return ResourceManager.GetString("dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديونية مطلوب خصمها.
        /// </summary>
        public static string debt_need_deduct {
            get {
                return ResourceManager.GetString("debt_need_deduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرار.
        /// </summary>
        public static string decision {
            get {
                return ResourceManager.GetString("decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ القرار.
        /// </summary>
        public static string decision_date {
            get {
                return ResourceManager.GetString("decision_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان القرار.
        /// </summary>
        public static string decision_title {
            get {
                return ResourceManager.GetString("decision_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع القرار.
        /// </summary>
        public static string decision_type {
            get {
                return ResourceManager.GetString("decision_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات.
        /// </summary>
        public static string decisions {
            get {
                return ResourceManager.GetString("decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المستحق عن التكافل.
        /// </summary>
        public static string deduct_amount_from_takaful {
            get {
                return ResourceManager.GetString("deduct_amount_from_takaful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف.
        /// </summary>
        public static string delete_confirmation {
            get {
                return ResourceManager.GetString("delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتداب لجهة خارجية.
        /// </summary>
        public static string deputation {
            get {
                return ResourceManager.GetString("deputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string destination_name {
            get {
                return ResourceManager.GetString("destination_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهات.
        /// </summary>
        public static string destinations {
            get {
                return ResourceManager.GetString("destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئول استمارات.
        /// </summary>
        public static string docments_user {
            get {
                return ResourceManager.GetString("docments_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوثيقة.
        /// </summary>
        public static string document_number {
            get {
                return ResourceManager.GetString("document_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الأشتراك.
        /// </summary>
        public static string document_subscription {
            get {
                return ResourceManager.GetString("document_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الوثيقة.
        /// </summary>
        public static string document_type {
            get {
                return ResourceManager.GetString("document_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الوثائق.
        /// </summary>
        public static string document_types {
            get {
                return ResourceManager.GetString("document_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوثائق.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل البنك.
        /// </summary>
        public static string edit_bank {
            get {
                return ResourceManager.GetString("edit_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل قرار.
        /// </summary>
        public static string edit_decision {
            get {
                return ResourceManager.GetString("edit_decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الجهة.
        /// </summary>
        public static string edit_destination {
            get {
                return ResourceManager.GetString("edit_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل وثيقة.
        /// </summary>
        public static string edit_document {
            get {
                return ResourceManager.GetString("edit_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل موظف.
        /// </summary>
        public static string edit_employee {
            get {
                return ResourceManager.GetString("edit_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الدرجة الوظيفية.
        /// </summary>
        public static string edit_grade {
            get {
                return ResourceManager.GetString("edit_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الأيصال.
        /// </summary>
        public static string edit_invoice {
            get {
                return ResourceManager.GetString("edit_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل أستماره.
        /// </summary>
        public static string edit_payment_form {
            get {
                return ResourceManager.GetString("edit_payment_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل نوع سداد.
        /// </summary>
        public static string edit_payment_type {
            get {
                return ResourceManager.GetString("edit_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string edit_user {
            get {
                return ResourceManager.GetString("edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الألكتروني.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الموظفين.
        /// </summary>
        public static string employee_data {
            get {
                return ResourceManager.GetString("employee_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وثائق الموظف.
        /// </summary>
        public static string employee_documents {
            get {
                return ResourceManager.GetString("employee_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم ملف الموظف.
        /// </summary>
        public static string employee_file_number {
            get {
                return ResourceManager.GetString("employee_file_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الموظف.
        /// </summary>
        public static string employee_name {
            get {
                return ResourceManager.GetString("employee_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموظف.
        /// </summary>
        public static string employee_number {
            get {
                return ResourceManager.GetString("employee_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الموظف.
        /// </summary>
        public static string employee_status {
            get {
                return ResourceManager.GetString("employee_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظفين.
        /// </summary>
        public static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انهاء خدمة.
        /// </summary>
        public static string end_of_service {
            get {
                return ResourceManager.GetString("end_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثي.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملفات.
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفية.
        /// </summary>
        public static string filtering {
            get {
                return ResourceManager.GetString("filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافي المبلغ المستحق للعضو.
        /// </summary>
        public static string final_paid {
            get {
                return ResourceManager.GetString("final_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم بالكامل.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة الوظيفية.
        /// </summary>
        public static string grade {
            get {
                return ResourceManager.GetString("grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجات الوظيفية.
        /// </summary>
        public static string grades {
            get {
                return ResourceManager.GetString("grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الخدمة.
        /// </summary>
        public static string in_service {
            get {
                return ResourceManager.GetString("in_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفُعل.
        /// </summary>
        public static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقساط مطلوب خصمها.
        /// </summary>
        public static string installment_need_deduct {
            get {
                return ResourceManager.GetString("installment_need_deduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقساط.
        /// </summary>
        public static string installments {
            get {
                return ResourceManager.GetString("installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة المرور غير صحيحة.
        /// </summary>
        public static string invalid_username_password {
            get {
                return ResourceManager.GetString("invalid_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الأيصال.
        /// </summary>
        public static string invoice_number {
            get {
                return ResourceManager.GetString("invoice_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيصالات.
        /// </summary>
        public static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر قسط تم سداده عن شهر.
        /// </summary>
        public static string last_paid_installment {
            get {
                return ResourceManager.GetString("last_paid_installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازة بدون مرتب.
        /// </summary>
        public static string leave_without_pay {
            get {
                return ResourceManager.GetString("leave_without_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول لنظام جمعية رعاية العاملين.
        /// </summary>
        public static string login_page_title {
            get {
                return ResourceManager.GetString("login_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string main_page {
            get {
                return ResourceManager.GetString("main_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الخزن.
        /// </summary>
        public static string manage_inventory {
            get {
                return ResourceManager.GetString("manage_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م. إدارية.
        /// </summary>
        public static string managerial_fees {
            get {
                return ResourceManager.GetString("managerial_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضوية و أشتراك.
        /// </summary>
        public static string member_and_subscription {
            get {
                return ResourceManager.GetString("member_and_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضوية فقط.
        /// </summary>
        public static string member_only {
            get {
                return ResourceManager.GetString("member_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العضوية.
        /// </summary>
        public static string membership_status {
            get {
                return ResourceManager.GetString("membership_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراك عضوية مستحق.
        /// </summary>
        public static string membership_subscription_deduct {
            get {
                return ResourceManager.GetString("membership_subscription_deduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومي.
        /// </summary>
        public static string national_id {
            get {
                return ResourceManager.GetString("national_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عنوان.
        /// </summary>
        public static string no_address {
            get {
                return ResourceManager.GetString("no_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملفات في الارشيف.
        /// </summary>
        public static string no_archive_documens {
            get {
                return ResourceManager.GetString("no_archive_documens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بريد الكتروني.
        /// </summary>
        public static string no_email {
            get {
                return ResourceManager.GetString("no_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مستندات.
        /// </summary>
        public static string no_files {
            get {
                return ResourceManager.GetString("no_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الشهور.
        /// </summary>
        public static string no_of_months {
            get {
                return ResourceManager.GetString("no_of_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد رقم هاتف.
        /// </summary>
        public static string no_phone {
            get {
                return ResourceManager.GetString("no_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اختيار نوع.
        /// </summary>
        public static string no_selected_gender {
            get {
                return ResourceManager.GetString("no_selected_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري الاعتماد.
        /// </summary>
        public static string ongoing_approve {
            get {
                return ResourceManager.GetString("ongoing_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيرادات أخرى.
        /// </summary>
        public static string other_income {
            get {
                return ResourceManager.GetString("other_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الصرف.
        /// </summary>
        public static string paid_off {
            get {
                return ResourceManager.GetString("paid_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صرف تكافل.
        /// </summary>
        public static string paid_takaful {
            get {
                return ResourceManager.GetString("paid_takaful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ السداد.
        /// </summary>
        public static string payment_date {
            get {
                return ResourceManager.GetString("payment_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الأستمارة.
        /// </summary>
        public static string payment_form_date {
            get {
                return ResourceManager.GetString("payment_form_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الاستمارة.
        /// </summary>
        public static string payment_form_view {
            get {
                return ResourceManager.GetString("payment_form_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستمارات.
        /// </summary>
        public static string payment_forms {
            get {
                return ResourceManager.GetString("payment_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الاستمارات.
        /// </summary>
        public static string payment_forms_management {
            get {
                return ResourceManager.GetString("payment_forms_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استمارات تكافل.
        /// </summary>
        public static string payment_forms_takaful {
            get {
                return ResourceManager.GetString("payment_forms_takaful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استمارات تصفية.
        /// </summary>
        public static string payment_forms_tasfya {
            get {
                return ResourceManager.GetString("payment_forms_tasfya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع السداد.
        /// </summary>
        public static string payment_type {
            get {
                return ResourceManager.GetString("payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع السداد.
        /// </summary>
        public static string payment_types {
            get {
                return ResourceManager.GetString("payment_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاش.
        /// </summary>
        public static string pension {
            get {
                return ResourceManager.GetString("pension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة.
        /// </summary>
        public static string percentage {
            get {
                return ResourceManager.GetString("percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        public static string primary_data {
            get {
                return ResourceManager.GetString("primary_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعاده تعيين.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرتب.
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر بنك.
        /// </summary>
        public static string select_bank {
            get {
                return ResourceManager.GetString("select_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختار قرار.
        /// </summary>
        public static string select_decision {
            get {
                return ResourceManager.GetString("select_decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع القرار.
        /// </summary>
        public static string select_decision_type {
            get {
                return ResourceManager.GetString("select_decision_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر الجهة.
        /// </summary>
        public static string select_destination {
            get {
                return ResourceManager.GetString("select_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر وثيقة.
        /// </summary>
        public static string select_document {
            get {
                return ResourceManager.GetString("select_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string select_documtn {
            get {
                return ResourceManager.GetString("select_documtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر الموظف.
        /// </summary>
        public static string select_employee {
            get {
                return ResourceManager.GetString("select_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الدرجة الوظيفية.
        /// </summary>
        public static string select_grade {
            get {
                return ResourceManager.GetString("select_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر نوع الوثيقة.
        /// </summary>
        public static string select_payment_type {
            get {
                return ResourceManager.GetString("select_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الصلاحية.
        /// </summary>
        public static string select_role {
            get {
                return ResourceManager.GetString("select_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار كلمة المرور.
        /// </summary>
        public static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الأشتراك.
        /// </summary>
        public static string subscription_date {
            get {
                return ResourceManager.GetString("subscription_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأشتراكات.
        /// </summary>
        public static string subscriptions {
            get {
                return ResourceManager.GetString("subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكافل.
        /// </summary>
        public static string takaful {
            get {
                return ResourceManager.GetString("takaful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفية.
        /// </summary>
        public static string tasfya {
            get {
                return ResourceManager.GetString("tasfya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الي.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم غير مفُعل.
        /// </summary>
        public static string user_not_actived {
            get {
                return ResourceManager.GetString("user_not_actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجازه من.
        /// </summary>
        public static string vacation_from {
            get {
                return ResourceManager.GetString("vacation_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجازه الى.
        /// </summary>
        public static string vacation_to {
            get {
                return ResourceManager.GetString("vacation_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
